# Define standardized school names and alternatives
STANDARD_SCHOOLS = {
    "Abby Kelley": [],
    "Abington": [],
    "NDA-Tyngsboro": [],
    "Pacific Rim": [],
    "Acton-Boxborough": [],
    "AMSA": ["Advanced Math & Science Academy Charter", "Adv. Math an"],
    "Agawam": [],
    "Algonquin": [],
    "Amesbury": [],
    "Amherst Pelham": [],
    "Andover": [],
    "Apponequet": [],
    "Archbishop Williams": ["Archbishop W"],
    "Arlington": [],
    "Arlington Catholic": [],
    "Ashland": [],
    "Assabet Valley": [],
    "Athol": [],
    "Atlantis Charter": [],
    "Attleboro": [],
    "Auburn": [],
    "Ayer Shirley": [],
    "Barnstable": [],
    "Bartlett": [],
    "Bay Path RVT": [],
    "Baystate Academy": [],
    "Bedford": [],
    "Belchertown": [],
    "Bellingham": [],
    "Belmont": [],
    "Beverly": [],
    "Billerica": [],
    "Bishop Feehan": [],
    "Bishop Fenwick": ["Bishop Fenwick HS", "Bishop Fenwick High School", "Bishop Fenwi"],
    "Bishop Stang": [],
    "Blackstone Valley": [],
    "Blackstone-Millville": ["Blackstone-Millville Reg", "Blackstone-M"],
    "Blue Hills": [],
    "Boston College": [],
    "Boston Collegiate Charter": [],
    "Boston Latin": [],
    "Boston Latin Academy": [],
    "Boston Prep": [],
    "Boston United": [],
    "Bourne": [],
    "Braintree": [],
    "Bridgewater-Raynham": [],
    "Brighton": [],
    "Bristol-Plymouth Reg Voc": [],
    "Brockton": [],
    "Bromfield": ["Bromfield Sc", "Bromfield School"],
    "Brooke Charter": [],
    "Brookline": [],
    "Burke": [],
    "Burlington": [],
    "Burncoat": [],
    "Cambridge R&L": [],
    "Canton": [],
    "Cape Cod Reg Tech": [],
    "Cardinal Spellman": [],
    "Carver": [],
    "Cathedral": [],
    "Catholic Memorial": [],
    "Central Catholic": [],
    "Charlestown": [],
    "Chelmsford": [],
    "Chelsea": [],
    "Chicopee": [],
    "Chicopee Comp": ["Chicopee Comprehensive"],
    "Clinton": [],
    "Codman": [],
    "Cohasset": [],
    "Collegiate Charter School of Lowell": [],
    "Community Charter of Cambridge": [],
    "Concord-Carlisle": [],
    "Cristo Rey": [],
    "Danvers": [],
    "Dartmouth": [],
    "David Prouty": [],
    "Dearborn STEM": [],
    "Dedham": [],
    "Dennis-Yarmouth": [],
    "Dighton-Rehoboth": [],
    "Diman Regional": [],
    "Doherty": [],
    "Douglas": [],
    "Dover-Sherborn": [],
    "Dracut": [],
    "Durfee": [],
    "Duxbury": [],
    "East Boston": [],
    "East Bridgewater": [],
    "East Longmeadow": [],
    "Easthampton": [],
    "Essex North Shore": [],
    "Everett": [],
    "Excel": [],
    "Excel Academy": [],
    "Fairhaven": [],
    "Falmouth": [],
    "Fitchburg": [],
    "Fontbonne": [],
    "Foxborough": [],
    "Framingham": [],
    "Franklin": [],
    "Franklin County": [],
    "Frontier": [],
    "Gardner": [],
    "Gloucester": [],
    "Grafton": [],
    "Greater Lawrence Tech": [],
    "Greater Lowell Tech": [],
    "Greater New Bedford RVT": [],
    "Greenfield": [],
    "Groton-Dunstable": [],
    "Hamilton-Wenham": [],
    "Hampden Charter East": [],
    "Hampden Charter West": [],
    "Hampshire": [],
    "Hanover": [],
    "Haverhill": [],
    "High School of Commerce": [],
    "Hingham": [],
    "Holbrook": [],
    "Holliston": [],
    "Holyoke": [],
    "Hoosac Valley": [],
    "Hopedale": [],
    "Hopkinton": [],
    "Hudson": [],
    "Hull": [],
    "Immaculate Heart": [],
    "Innovation Academy": [],
    "Ipswich": [],
    "John J. Duggan": [],
    "Joseph Case": [],
    "Keefe": [],
    "King Philip": [],
    "KIPP Academy": [],
    "Lawrence": [],
    "Leicester": [],
    "Lenox": [],
    "Leominster": [],
    "Lexington": [],
    "Libertas Academy Charter": [],
    "Lincoln-Sudbury": ["L-S"],
    "Littleton": ["Littleton HS", "Littleton High School", "LITT"],
    "Longmeadow": [],
    "Lowell": [],
    "Ludlow": [],
    "Lunenburg": [],
    "Lynn Classical": [],
    "Lynn English": [],
    "Lynn Vocational": [],
    "Lynnfield": [],
    "Mahar Regional": [],
    "Malden": [],
    "Malden Catholic": [],
    "Mansfield": [],
    "Marblehead": [],
    "Marlborough": [],
    "Marshfield": [],
    "Martha's Vineyard": ["Marthas Vine"],
    "Masconomet": [],
    "Mashpee": [],
    "Maynard": [],
    "Medfield": [],
    "Medford": [],
    "Medway": [],
    "Melrose": [],
    "Methuen": [],
    "Middleboro": [],
    "Milford": [],
    "Millbury": [],
    "Millis": [],
    "Milton": [],
    "Minnechaug": [],
    "Mohawk Trail": [],
    "Monomoy": [],
    "Monson": [],
    "Montachusett": [],
    "Monument Mountain": [],
    "Mount Everett": ["Mt Everett"],
    "Mt Greylock": [],
    "Murdock": [],
    "Mystic Valley": [],
    "Nantucket": [],
    "Narragansett": [],
    "Nashoba": [],
    "Nashoba Valley": [],
    "Natick": [],
    "Nauset": [],
    "Needham": [],
    "Neighborhood House": [],
    "New Bedford": [],
    "New Heights": [],
    "New Mission": [],
    "Newburyport": [],
    "Newton North": [],
    "Newton South": [],
    "Nipmuc": [],
    "Norfolk County": [],
    "North Andover": [],
    "North Attleborough": [],
    "North Middlesex": [],
    "North Quincy": [],
    "North Reading": [],
    "Northampton": [],
    "Northbridge": [],
    "Northeast Metro": [],
    "Norton": [],
    "Norwell": [],
    "Norwood": [],
    "NDA-Hingham": [],
    "NDA-Worcester": [],
    "O'Bryant": [],
    "Oakmont": [],
    "Old Rochester": [],
    "Oliver Ames": [],
    "Oxford": [],
    "Palmer": [],
    "Parker Charter": [],
    "Peabody": [],
    "Pembroke": [],
    "Pentucket": [],
    "Pioneer Charter I": [],
    "Pioneer Charter II": [],
    "Pioneer Valley Christian": [],
    "Pioneer Valley": [],
    "Pittsfield": [],
    "Plymouth North": [],
    "Plymouth South": [],
    "Pope Francis": [],
    "Prospect Hill": [],
    "Putnam": [],
    "Quabbin": [],
    "Quaboag": [],
    "Randolph": [],
    "Reading": [],
    "Revere": [],
    "Riverview": [],
    "Rockland": [],
    "Roxbury Prep": [],
    "St. John's-Shrewsbury": [],
    "St. John's Prep": [],
    "Saint Mary's": [],
    "Saint Paul Diocesan": [],
    "Salem": [],
    "Salem Academy": [],
    "Sandwich": [],
    "Saugus": [],
    "Scituate": [],
    "Seekonk": [],
    "Sharon": [],
    "Shawsheen Valley": [],
    "Shepherd Hill": [],
    "Shrewsbury": [],
    "Silver Lake": [],
    "Snowden": [],
    "Somerset Berkley": [],
    "Somerville": [],
    "South Hadley": [],
    "South High": [],
    "South Shore": [],
    "South Shore Christian": ["South Shore Christian Academy"],
    "South Shore Reg": ["South Shore Voc Tech", "South Shore Vocational", "South Shore Vocational Tech"],
    "Southbridge": [],
    "Southeastern Reg": [],
    "Southwick": ["Southwick-To"],
    "Springfield Central": [],
    "Springfield HS of Science": ["Springfield High School of Science"],
    "Springfield International": [],
    "Stoneham": [],
    "Stoughton": [],
    "Sturgis West": [],
    "Sutton": [],
    "Swampscott": [],
    "Taconic": [],
    "Tahanto": [],
    "Tantasqua": [],
    "Taunton": [],
    "TEC Connections": [],
    "Tech Boston": ["TechBoston Academy"],
    "Tewksbury": [],
    "Tri-County RVT": [],
    "Triton": [],
    "Turners Falls": [],
    "Tyngsborough": [],
    "University Park": [],
    "Ursuline Academy": ["Ursuline Aca"],
    "Uxbridge": [],
    "Wachusett": [],
    "Wahconah": [],
    "Wakefield": [],
    "Walpole": [],
    "Waltham": [],
    "Wareham": [],
    "Watertown": [],
    "Wayland": [],
    "Wellesley": [],
    "West Bridgewater": [],
    "West Springfield": [],
    "Westborough": [],
    "Westfield": [],
    "Westford": [],
    "Weston": [],
    "Westwood": [],
    "Weymouth": [],
    "Whitinsville Christian": [],
    "Whitman-Hanson": ["Whitman Hanson"],
    "Whittier Regional": ["Whittier"],
    "Wilmington": [],
    "Winchester": [],
    "Winthrop": [],
    "Woburn": [],
    "Worcester Tech": [],
    "Xaverian Brothers": [],
    "Sabis Intl": ["Sabis International"],
    "Sturgis East": []
}